angular.module('scroll').directive('swipeToDelete', ['touchAnimation', 'animationUtils', function(touchAnimation, animationUtils) {
  return {
    link: function(scope, element, attrs) {
      // TODO:
      // - animate back when scrolling starts
      //   or if user clicked on another element!
      //   --> effect is responsible for this as well!
      // - show buttons behind the element:
      //   should be part of the template, i.e. not
      //   generated by the directive!
      // - rename this directive to: swipeLeftOptions

      var anim = new Animation(element[0], [
        { offset: 0, transform: 'translateZ(0) translateX(0%)' },
        { offset: 1, transform: 'translateZ(0) translateX(-60%)' }
      ], {
        duration: 1
      });
      anim.name = 'main';

      var width = element.width();
      touchAnimation({
        animation: anim,
        effects: [{
          animationName: 'main',
          listener: swipeEffect
        }],
        timeToPixelRatio: width * -1,
        gesture: {type: 'x', element: element}
      });

      function swipeEffect(event) {
        var diffStart = Math.abs(event.currentTime - event.animation.startTime),
          diffEnd = Math.abs(event.currentTime - event.animation.endTime),
          targetTime;

        if (diffStart > diffEnd) {
          targetTime = event.animation.endTime;
        } else {
          targetTime = event.animation.startTime;
        }
        return {
          targetTime: targetTime,
          duration: 0.5,
          easing: 'ease-out'
        };
      }
    }
  };
}]);