angular.module('scroll').directive('swipeToDelete', ['touchAnimation', 'animationUtils', function(touchAnimation, animationUtils) {
  return {
    link: function(scope, element, attrs) {
      // TODO:
      // - animate back when scrolling starts
      //   or if user clicked on another element!
      //   --> effect is responsible for this as well!
      // - show buttons behind the element:
      //   should be part of the template, i.e. not
      //   generated by the directive!
      // - rename this directive to: swipeLeftOptions

      var width = element.width();
      touchAnimation({
        animationFactory: animationFactory,
        effects: [swipeEffect],
        gesture: {type: 'x', element: element}
      });

      function animationFactory(animationSpec) {
        animationSpec.main = {
          target: element[0],
          type: 'atom',
          effect: [
            { offset: 0, transform: 'translateZ(0) translateX(0%)' },
            { offset: 1, transform: 'translateZ(0) translateX(-60%)' }
          ],
          timing: {
            duration: width
          }
        };
      }

      function swipeEffect(event, touchAnimation) {
        var animation = touchAnimation.getAnimationByName('main');
        var diffStart = Math.abs(event.currentTime - animation.startTime),
          diffEnd = Math.abs(event.currentTime - animation.endTime),
          targetTime;

        if (diffStart > diffEnd) {
          targetTime = animation.endTime;
        } else {
          targetTime = animation.startTime;
        }
        return {
          targetTime: targetTime,
          duration: 0.5,
          easing: 'ease-out'
        };
      }
    }
  };
}]);